name: Weekly NPM Stats Report

on:
  schedule:
    - cron: "0 8 * * 1" # Every Monday at 08:00 UTC
  workflow_dispatch:

jobs:
  generate-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install jq
        run: sudo apt-get install jq

      - name: Fetch and Save NPM Stats
        run: |
          curl "https://api.npmjs.org/downloads/point/last-week/responsive-style-kit" | jq '.' > npm-downloads.json
